### ISSUE TITLE
Не работает загрузка обложек

### ISSUE THREAD

**Issue by aaa4xu** [anilibria/anilibria-docker#8]
```
Fatal error:  Uncaught Error: Call to undefined function exif_imagetype() in /var/www/private/func.php:1257
Stack trace:
#0 /var/www/private/func.php(1360): uploadPoster('1')
#1 /var/www/public/release/index.php(11): xrelease()
#2 {main}
  thrown in /var/www/private/func.php on line 1257
```
Видимо, не хватает какого-то модуля php для работы с картинками.

**Comment by Asethon** [comment]
Исправлено

https://github.com/anilibria/anilibria-docker/commit/871f55c13d2bf15b5f62094fe3b51fb92cbd21e6
